<a href="https://colab.research.google.com/github/LeonardoHyppolito/Estudos/blob/main/Lista_2_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importando biblioteca pandas
import pandas as pd

In [2]:
#Lendo arquivo 
df = pd.read_csv("campeonato-brasileiro-full.csv")

1) Calcule para todas as observações a diferença entre as colunas Mandante Placar e Visitante Placar. Faça isso preenchendo as lacunas!

In [8]:
df.loc[:, ["mandante_placar","visitante_placar"]] # Utilizando o loc[], para selecionar as colunas desejadas através do nome. 
# O primeiro parâmetro nos diz quantas informações eu quero pegar, e quais são elas, passando : , (vazio dos dois lados), ele pegará todas as 
#informações das colunas escolhidas.

      mandante_placar  visitante_placar
0                   4                 2
1                   2                 0
2                   1                 1
3                   2                 2
4                   1                 1
...               ...               ...
7640                1                 0
7641                1                 1
7642                1                 0
7643                4                 3
7644                1                 1

[7645 rows x 2 columns]

In [9]:
#Também poderiamos fazer utilizando o iloc[], e passando os indices das colunas desejadas.

In [14]:
# Fazendo a função de subtração, de modo anonima. (lambda)
df.loc[:, ["mandante_placar","visitante_placar"]].apply(lambda x: x.max() - x.min(), axis=1) # Ja que queremos a diferença em módulo. 
# O computador nos retorna o index e o resultado da subtração do maximo e do mínimo. axis=1, pois precisamos dos valores das linhas.

0       2
1       2
2       0
3       0
4       0
       ..
7640    1
7641    0
7642    1
7643    1
7644    0
Length: 7645, dtype: int64

2) Crie um MultiIndex para o DataFrame com as colunas Dia e Estado Mandante

In [16]:
#Visualização rapida.
df.head(2)

,ID,rodada,data,hora,dia,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_placar,visitante_placar,mandante_estado,visitante_estado,estado_vencedor
0,1,1,2003-03-29,16:00,Sabado,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,brinco de ouro,4,2,SP,RJ,SP
1,2,1,2003-03-29,16:00,Sabado,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,arena da baixada,2,0,PR,RS,PR

In [18]:
# Criando multiplos index. 
df.set_index(["dia", "mandante_estado"], inplace = True)

In [20]:
#Conferindo se deu certo
df.head(2)

                        ID  rodada        data   hora      mandante visitante  \
dia    mandante_estado
Sabado SP                1       1  2003-03-29  16:00       Guarani     Vasco
       PR                2       1  2003-03-29  16:00  Athletico-PR    Gremio

                       formacao_mandante formacao_visitante tecnico_mandante  \
dia    mandante_estado
Sabado SP                            NaN                NaN              NaN
       PR                            NaN                NaN              NaN

                       tecnico_visitante      vencedor             arena  \
dia    mandante_estado
Sabado SP                            NaN       Guarani    brinco de ouro
       PR                            NaN  Athletico-PR  arena da baixada

                        mandante_placar  visitante_placar visitante_estado  \
dia    mandante_estado
Sabado SP                             4                 2               RJ
       PR                             2                 0               RS

                       estado_vencedor
dia    mandante_estado
Sabado SP                           SP
       PR                           PR

3) Classifique os dois níveis de índice em ordem crescente e salve no próprio DataFrame

In [26]:
# Colocando em ordem crescente com ascending=True, e salvando com inplace = True
df.sort_index(ascending= True, inplace=True)

In [27]:
df.head(10) # Visualizando e conferindo

                           ID  rodada        data   hora mandante  \
dia     mandante_estado
Domingo AL               6532       3  2019-05-05  16:00      CSA
        AL               6582       8  2019-06-09  19:01      CSA
        AL               6663      16  2019-08-25  19:00      CSA
        AL               6685      18  2019-09-08  19:00      CSA
        AL               6702      20  2019-09-22  16:01      CSA
        AL               6735      23  2019-10-06  19:00      CSA
        AL               6824      32  2019-11-10  19:01      CSA
        AL               6861      36  2019-12-01  17:58      CSA
        AL               6879      38  2019-12-08  16:01      CSA
        BA                 10       1  2003-03-30  16:00  Vitoria

                           visitante formacao_mandante formacao_visitante  \
dia     mandante_estado
Domingo AL                    Santos           4-2-3-1              3-4-3
        AL               Botafogo-RJ           4-2-3-1            4-1-4-1
        AL                  Cruzeiro         4-1-2-1-2            4-2-3-1
        AL               Chapecoense         4-1-2-1-2            4-2-3-1
        AL                     Ceara           4-2-3-1            4-2-3-1
        AL                      Avai             4-3-3            4-1-4-1
        AL                     Vasco           4-2-3-1            4-2-3-1
        AL                     Bahia           4-2-3-1              4-3-3
        AL                 Sao Paulo           4-2-3-1              4-3-3
        BA               Figueirense               NaN                NaN

                                  tecnico_mandante          tecnico_visitante  \
dia     mandante_estado
Domingo AL                        J. Sampaoli Moya           J. Sampaoli Moya
        AL                     E. de Souza Barroca        E. de Souza Barroca
        AL                                 R. Ceni                    R. Ceni
        AL                             E. Hartkopp                E. Hartkopp
        AL                        E. Alves Moreira           E. Alves Moreira
        AL               A. Valentim do Carmo Neto  A. Valentim do Carmo Neto
        AL                  V. Luxemburgo da Silva     V. Luxemburgo da Silva
        AL                      R. Machado Marques         R. Machado Marques
        AL                          F. Diniz Silva             F. Diniz Silva
        BA                                     NaN                        NaN

                            vencedor             arena  mandante_placar  \
dia     mandante_estado
Domingo AL                         -  estadio rei pele                0
        AL               Botafogo-RJ  estadio rei pele                1
        AL                         -  estadio rei pele                1
        AL                       CSA  estadio rei pele                2
        AL                       CSA  estadio rei pele                1
        AL                       CSA  estadio rei pele                3
        AL                     Vasco  estadio rei pele                0
        AL                     Bahia  estadio rei pele                1
        AL                 Sao Paulo  estadio rei pele                1
        BA                         -          barradao                1

                         visitante_placar visitante_estado estado_vencedor
dia     mandante_estado
Domingo AL                              0               SP               -
        AL                              2               RJ              RJ
        AL                              1               MG               -
        AL                              0               SC              AL
        AL                              0               CE              AL
        AL                              1               SC              AL
        AL                              3               RJ              RJ
        AL                              2               BA              BA
        AL                              2               SP              SP
        BA                              1               SC               -

4) Inspecione o DataFrame

In [28]:
# Primeira etapa da inspeção, visualizando com df.head()
df.head()

                           ID  rodada        data   hora mandante  \
dia     mandante_estado
Domingo AL               6532       3  2019-05-05  16:00      CSA
        AL               6582       8  2019-06-09  19:01      CSA
        AL               6663      16  2019-08-25  19:00      CSA
        AL               6685      18  2019-09-08  19:00      CSA
        AL               6702      20  2019-09-22  16:01      CSA

                           visitante formacao_mandante formacao_visitante  \
dia     mandante_estado
Domingo AL                    Santos           4-2-3-1              3-4-3
        AL               Botafogo-RJ           4-2-3-1            4-1-4-1
        AL                  Cruzeiro         4-1-2-1-2            4-2-3-1
        AL               Chapecoense         4-1-2-1-2            4-2-3-1
        AL                     Ceara           4-2-3-1            4-2-3-1

                            tecnico_mandante    tecnico_visitante  \
dia     mandante_estado
Domingo AL                  J. Sampaoli Moya     J. Sampaoli Moya
        AL               E. de Souza Barroca  E. de Souza Barroca
        AL                           R. Ceni              R. Ceni
        AL                       E. Hartkopp          E. Hartkopp
        AL                  E. Alves Moreira     E. Alves Moreira

                            vencedor             arena  mandante_placar  \
dia     mandante_estado
Domingo AL                         -  estadio rei pele                0
        AL               Botafogo-RJ  estadio rei pele                1
        AL                         -  estadio rei pele                1
        AL                       CSA  estadio rei pele                2
        AL                       CSA  estadio rei pele                1

                         visitante_placar visitante_estado estado_vencedor
dia     mandante_estado
Domingo AL                              0               SP               -
        AL                              2               RJ              RJ
        AL                              1               MG               -
        AL                              0               SC              AL
        AL                              0               CE              AL

In [31]:
# Segunda etapa da inspeção, com df.info
df.info() # Assim vemos que realmente é um multiIndex.

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7645 entries, ('Domingo', 'AL') to ('Terça-feira', 'SP')
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  7645 non-null   int64
 1   rodada              7645 non-null   int64
 2   data                7645 non-null   object
 3   hora                7645 non-null   object
 4   mandante            7645 non-null   object
 5   visitante           7645 non-null   object
 6   formacao_mandante   2671 non-null   object
 7   formacao_visitante  2671 non-null   object
 8   tecnico_mandante    3035 non-null   object
 9   tecnico_visitante   3035 non-null   object
 10  vencedor            7645 non-null   object
 11  arena               7645 non-null   object
 12  mandante_placar     7645 non-null   int64
 13  visitante_placar    7645 non-null   int64
 14  visitante_estado    7645 non-null   object
 15  estado_vencedor     7645 non-null   object
dtypes: int64(4), object(12)
memory usage: 971.7+ KB

5) Selecione todos os jogos com "Estado Mandante" sendo o RJ

In [37]:
# Primeiro precisamos resetar nosso indice, para que o estado mandante volte a ser uma coluna 
df.reset_index(inplace=True)

In [38]:
df.head()

,index,dia,mandante_estado,ID,rodada,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_placar,visitante_placar,visitante_estado,estado_vencedor
0,0,Domingo,AL,6532,3,2019-05-05,16:00,CSA,Santos,4-2-3-1,3-4-3,J. Sampaoli Moya,J. Sampaoli Moya,-,estadio rei pele,0,0,SP,-
1,1,Domingo,AL,6582,8,2019-06-09,19:01,CSA,Botafogo-RJ,4-2-3-1,4-1-4-1,E. de Souza Barroca,E. de Souza Barroca,Botafogo-RJ,estadio rei pele,1,2,RJ,RJ
2,2,Domingo,AL,6663,16,2019-08-25,19:00,CSA,Cruzeiro,4-1-2-1-2,4-2-3-1,R. Ceni,R. Ceni,-,estadio rei pele,1,1,MG,-
3,3,Domingo,AL,6685,18,2019-09-08,19:00,CSA,Chapecoense,4-1-2-1-2,4-2-3-1,E. Hartkopp,E. Hartkopp,CSA,estadio rei pele,2,0,SC,AL
4,4,Domingo,AL,6702,20,2019-09-22,16:01,CSA,Ceara,4-2-3-1,4-2-3-1,E. Alves Moreira,E. Alves Moreira,CSA,estadio rei pele,1,0,CE,AL

In [36]:
df.loc["mandante_estado"] == "RJ"

KeyError: ignored

6) Selecione todos os jogos com "Estado Mandante" sendo o RJ que ocorreram no Sábado

7) Selecione todos os jogos com o "Estado Mandante" sendo o "RS" e "SP" que ocorreram no "Sábado" e apenas as colunas "Arena" e "Rodada"!

8) Troque os níveis do MultiIndex e classifique o novo MultiIndex em ordem crescente!

9) Converta todos os elementos na coluna Estado Mandante para lower!

10) Verifique quantos dias na coluna "Dia" contêm "feira"!